name: internet_time
description: For all your Swatch Internet Time needs.
version: 0.0.2
repository: https://github.com/ilmalte/internet_time
issue_tracker: https://github.com/ilmalte/internet_time/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
